name: Generate NAMESPACE file
run-name: ${{ github.actor }} is generating NAMESPACE file
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  Generating-NAMESPACE-file:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: R Build and Checks
        uses: Swechhya/R-actions@v1.2
        with:
          action: 'all'
          needsBioc: true
          buildSubDirectory: './'
      - name: Upload NAMESPACE file
      - run: |
          git config user.name ruiheesi
          git config user.email rui.he@nih.gov
          git add ./NAMESPACE
          git commit -amend -m "generated NAMESPACE"
          git push
        
      
    
          
          
