name: Generate NAMESPACE file
run-name: ${{ github.actor }} is generating NAMESPACE file
on: [push]
jobs:
  Generating-NAMESPACE-file:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: R Build and Checks
        uses: Swechhya/R-actions@v1.2
        with:
          action: 'all'
          needsBioc: true
          buildSubDirectory: './'
  Upload-NAMESPACE:
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name ruiheesi
          git config user.email rui.he@nih.gov
          git add .
          git commit -m "generated NAMESPACE"
          git push
        
      
    
          
          
